### ISSUE TITLE
[OSX] The OS window has no min-width/min-height

### ISSUE THREAD

**Issue by fullreset** [quadrupleslap/tether#14]
Ideally, this would be a configuration/builder option -- to avoid sizes that are ridiculous or problematic. The attachment shows the worst case. ^^

<img width="135" alt="screen shot 2018-03-02 at 03 27 30" src="https://user-images.githubusercontent.com/13809698/36865287-07fb7448-1dca-11e8-82a1-adb5b13eda67.png">

This issue may not manifest in the same way elsewhere ...

**Comment by quadrupleslap** [comment]
That doesn't look good at all! I'm not sure if I should just set the minimum width/height to the initial width/height, as I think it currently is on Linux, or if there should be another pair of fields for the minimum width/height.

**Comment by fullreset** [comment]
The quick fix would be to set minimums; the ideal fix would be to set reasonable minimums and allow those to be overrided.

**Comment by quadrupleslap** [comment]
Current workaround on master:
- On Linux and macOS, the minimum height is defined to be the initial height.
- On Windows 10, I think that the OS gets to choose the minimum size.

Is this okay? I don't think adding a configurable minimum size would be a good idea, because it would mean nothing on Windows/iOS/Android (then again, the same could be said of the 'initially fullscreen' option, so I might be wrong.)

**Comment by fullreset** [comment]
As you say, this is a bit like the fullscreen thing -- it won't really make sense everywhere. 

But for the best user experience I'd expect to be able to set a "good" size to start (for desktops/laptops), and the minimum size is the size below which the application is no longer very usable. So if no minimum is set, then there is no minimum; if a minimum doesn't make sense because I'm on iOS or Android then it can just be ignored. 

This gives us a good usable starting point (initial size), without being greedy (fullscreen), and a lower bound on size to make sure the app doesn't look silly. :) 

I think this makes more sense than forcing the application's initial size to be the minimum size...

**Comment by quadrupleslap** [comment]
Okay, that should be a pretty straightforward patch. I'll try implementing it tomorrow.

**Comment by quadrupleslap** [comment]
The changes that need to be made are:

- add `min_size` method on `Options`, and the corresponding fields. I think that the builder should set the minimum size to the default size by default.
- set the privacy of all `Options` fields to `pub(crate)` because then fields can be added in the future without making breaking changes.
- implement for each operating system.
  - on windows, this means setting `PreferredMinSize` *and* `PreferredSize`.
  - on macOS, this means setting `ContentMinSize` *and* `ContentSize`.
  - on Linux, this means calling `set_size_request` (minimum size) and `set_default_size`.

**Comment by quadrupleslap** [comment]
Done! @fullreset, if it looks alright to you, I'll go ahead and publish it! Changes to the API:

- Added `Options::minimum_size(self, usize, usize) -> Self`.
- All `Options` fields are now `pub(crate)`.

**Comment by fullreset** [comment]
Sounds good @quadrupleslap -- I will give a poke in the next day or two. Thanks!
